# Generated by Django 5.2.7 on 2025-10-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bale',
            options={'verbose_name': ('Fardo',), 'verbose_name_plural': 'Fardos'},
        ),
    ]
