# Generated by Django 5.2.7 on 2025-10-27 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_bale_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bale',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='bale',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='bale',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='bale',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra'),
        ),
        migrations.AlterField(
            model_name='bale',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='bale',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('SOLD', 'Vendido'), ('RESERVED', 'Separado')], default='AVAILABLE', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bale',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Proveedor'),
        ),
    ]
