# Generated by Django 5.2.7 on 2025-10-27 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_bale_warehouse_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaleMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('type', models.CharField(choices=[('RECEIVED', 'Recepción'), ('RESERVED', 'Separado'), ('SOLD', 'Vendido'), ('TRANSFER', 'Traslado')], max_length=20, verbose_name='Tipo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('bale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.bale')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
