# Generated by Django 5.2.7 on 2025-10-27 20:46

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_brand_bale_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagen')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('bale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.bale')),
            ],
            options={
                'verbose_name': 'Imagen de fardo',
                'verbose_name_plural': 'Imagenes de fardos',
            },
        ),
    ]
